# "Back to Basics", but "fun" this time

We're going to go back-to-basics, but we are going to use real geospatial data to hopefully make it a bit more fun.

In [1]:
import geopandas as gpd

We're going to look at the EPA Ecoregions for this: https://www.epa.gov/eco-research/level-iii-and-iv-ecoregions-continental-united-states

In [2]:
epa_files = gpd.read_file("../example_data/us_eco_l3_state_boundaries/us_eco_l3_state_boundaries.shp")

In [5]:
epa_files

,US_L3CODE,US_L3NAME,NA_L3CODE,NA_L3NAME,NA_L2CODE,NA_L2NAME,NA_L1CODE,NA_L1NAME,STATE_NAME,EPA_REGION,L3_KEY,L2_KEY,L1_KEY,geometry
0,1,Coast Range,7.1.8,Coast Range,7.1,MARINE WEST COAST FOREST,7,MARINE WEST COAST FOREST,California,9,1 Coast Range,7.1 MARINE WEST COAST FOREST,7 MARINE WEST COAST FOREST,"POLYGON ((-2284145.646 1942003.86, -2284260.19..."
1,1,Coast Range,7.1.8,Coast Range,7.1,MARINE WEST COAST FOREST,7,MARINE WEST COAST FOREST,California,9,1 Coast Range,7.1 MARINE WEST COAST FOREST,7 MARINE WEST COAST FOREST,"POLYGON ((-2326859.904 1961336.254, -2326870.1..."
2,1,Coast Range,7.1.8,Coast Range,7.1,MARINE WEST COAST FOREST,7,MARINE WEST COAST FOREST,California,9,1 Coast Range,7.1 MARINE WEST COAST FOREST,7 MARINE WEST COAST FOREST,"POLYGON ((-2326706.425 1962413.547, -2326701.8..."
3,1,Coast Range,7.1.8,Coast Range,7.1,MARINE WEST COAST FOREST,7,MARINE WEST COAST FOREST,California,9,1 Coast Range,7.1 MARINE WEST COAST FOREST,7 MARINE WEST COAST FOREST,"POLYGON ((-2328276.727 1965731.514, -2328270.7..."
4,1,Coast Range,7.1.8,Coast Range,7.1,MARINE WEST COAST FOREST,7,MARINE WEST COAST FOREST,California,9,1 Coast Range,7.1 MARINE WEST COAST FOREST,7 MARINE WEST COAST FOREST,"POLYGON ((-2332682.748 1971271.442, -2332679.6..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1626,85,Southern California/Northern Baja Coast,11.1.1,"California Coastal Sage, Chaparral, and Oak Wo...",11.1,MEDITERRANEAN CALIFORNIA,11,MEDITERRANEAN CALIFORNIA,California,9,85 Southern California/Northern Baja Coast,11.1 MEDITERRANEAN CALIFORNIA,11 MEDITERRANEAN CALIFORNIA,"POLYGON ((-2207921.025 1508177.661, -2207906.5..."
1627,85,Southern California/Northern Baja Coast,11.1.1,"California Coastal Sage, Chaparral, and Oak Wo...",11.1,MEDITERRANEAN CALIFORNIA,11,MEDITERRANEAN CALIFORNIA,California,9,85 Southern California/Northern Baja Coast,11.1 MEDITERRANEAN CALIFORNIA,11 MEDITERRANEAN CALIFORNIA,"POLYGON ((-2200157.466 1552356.151, -2199525.8..."
1628,9,Eastern Cascades Slopes and Foothills,6.2.8,Eastern Cascades Slopes and Foothills,6.2,WESTERN CORDILLERA,6,NORTHWESTERN FORESTED MOUNTAINS,California,9,9 Eastern Cascades Slopes and Foothills,6.2 WESTERN CORDILLERA,6 NORTHWESTERN FORESTED MOUNTAINS,"POLYGON ((-2116655.752 2403474.894, -2115275.6..."
1629,9,Eastern Cascades Slopes and Foothills,6.2.8,Eastern Cascades Slopes and Foothills,6.2,WESTERN CORDILLERA,6,NORTHWESTERN FORESTED MOUNTAINS,Oregon,10,9 Eastern Cascades Slopes and Foothills,6.2 WESTERN CORDILLERA,6 NORTHWESTERN FORESTED MOUNTAINS,"POLYGON ((-1957369.067 2786198.451, -1956133.1..."
1630,9,Eastern Cascades Slopes and Foothills,6.2.8,Eastern Cascades Slopes and Foothills,6.2,WESTERN CORDILLERA,6,NORTHWESTERN FORESTED MOUNTAINS,Washington,10,9 Eastern Cascades Slopes and Foothills,6.2 WESTERN CORDILLERA,6 NORTHWESTERN FORESTED MOUNTAINS,"POLYGON ((-1846221.209 2944197.938, -1845820.8..."

In [7]:
for index, row in epa_files.iterrows():
    print(f"{index}, {row.loc["EPA_REGION"]}")
    break

0, 9

In [8]:
for index, row in epa_files.iterrows():
    print(f"{index}, {row["EPA_REGION"]}")
    break

0, 9

In [9]:
epa_region_counts = dict()
for index, row in epa_files.iterrows():
    print(f"{index}, {row["EPA_REGION"]}")
    epa_region_counts[row["EPA_REGION"]] +=1
    break

0, 9

KeyError: 9

In [10]:
epa_region_counts = dict()
for index, row in epa_files.iterrows():
    cur_epa_reg = row['EPA_REGION']
    if cur_epa_reg in epa_region_counts:
        epa_region_counts[cur_epa_reg]+=1
    else:
        epa_region_counts[cur_epa_reg] = 1

epa_region_counts

{9: 85, 10: 102, 8: 74, 6: 327, 7: 65, 4: 361, 3: 190, 5: 110, 1: 189, 2: 128}

In [11]:
total_count = 0
for key in epa_region_counts:
    total_count += epa_region_counts[key]

In [12]:
total_count

1631

In [10]:
epa_files.groupby("EPA_REGION").count()

,US_L3CODE,US_L3NAME,NA_L3CODE,NA_L3NAME,NA_L2CODE,NA_L2NAME,NA_L1CODE,NA_L1NAME,STATE_NAME,L3_KEY,L2_KEY,L1_KEY,geometry
EPA_REGION,,,,,,,,,,,,,
1,189,189,189,189,189,189,189,189,189,189,189,189,189
2,128,128,128,128,128,128,128,128,128,128,128,128,128
3,190,190,190,190,190,190,190,190,190,190,190,190,190
4,361,361,361,361,361,361,361,361,361,361,361,361,361
5,110,110,110,110,110,110,110,110,110,110,110,110,110
6,327,327,327,327,327,327,327,327,327,327,327,327,327
7,65,65,65,65,65,65,65,65,65,65,65,65,65
8,74,74,74,74,74,74,74,74,74,74,74,74,74
9,85,85,85,85,85,85,85,85,85,85,85,85,85
10,102,102,102,102,102,102,102,102,102,102,102,102,102